export enum MessageErrorForms {
  REQUIRED = 'WINK.FORMS.ERROR.REQUIRED',
  MAXIMUM = 'WINK.FORMS.ERROR.MAXIMUM',
  EMAIL = 'WINK.FORMS.ERROR.EMAIL',
  URL = 'WINK.FORMS.ERROR.URL',
  MINIMUM = 'WINK.FORMS.ERROR.MINIMUM',
  CHARACTER = 'WINK.FORMS.ERROR.CHARACTER',
  WHITE_SPACE = 'WINK.FORMS.ERROR.WHITE_SPACE'
}
